package net.villenium.skywars.game.generators;

import net.villenium.skywars.utils.simple.SimpleItemStack;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.List;

public class ClassicGenerator extends ChestGenerator {
    public ClassicGenerator() {
        super(5, 8);
    }

    protected List<List<ItemStack>> getDefaultItems() {
        List<List<ItemStack>> items = new ArrayList();
        List<ItemStack> list = new ArrayList();
        this.add(list, new ItemStack(Material.STONE_SWORD, 1), 2);
        this.add(list, new ItemStack(Material.IRON_SWORD, 1), 4);
        this.add(list, new ItemStack(Material.DIAMOND_SWORD, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.CHAINMAIL_HELMET, 1), 4);
        this.add(list, new ItemStack(Material.IRON_HELMET, 1), 2);
        this.add(list, new ItemStack(Material.DIAMOND_HELMET, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.CHAINMAIL_CHESTPLATE, 1), 3);
        this.add(list, new ItemStack(Material.IRON_CHESTPLATE, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.CHAINMAIL_LEGGINGS, 1), 4);
        this.add(list, new ItemStack(Material.IRON_LEGGINGS, 1), 2);
        this.add(list, new ItemStack(Material.DIAMOND_LEGGINGS, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.CHAINMAIL_BOOTS, 1), 3);
        this.add(list, new ItemStack(Material.IRON_BOOTS, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.EGG, 16), 2);
        this.add(list, new ItemStack(Material.SNOW_BALL, 16), 2);
        this.add(list, new ItemStack(Material.FISHING_ROD, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.COOKED_BEEF, 8), 1);
        this.add(list, new ItemStack(Material.COOKED_CHICKEN, 8), 2);
        this.add(list, new ItemStack(Material.COOKED_FISH, 8), 1);
        this.add(list, new ItemStack(Material.APPLE, 8), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.WATER_BUCKET, 1), 4);
        this.add(list, new ItemStack(Material.LAVA_BUCKET, 1), 2);
        this.add(list, new ItemStack(Material.ENCHANTMENT_TABLE, 1), 2);
        this.add(list, new ItemStack(Material.SANDSTONE, 24), 2);
        this.add(list, new ItemStack(Material.SAND, 24), 1);
        this.add(list, new ItemStack(Material.IRON_PICKAXE, 1), 1);
        this.add(list, new ItemStack(Material.IRON_AXE, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.WOOD, 28), 4);
        this.add(list, new ItemStack(Material.STONE, 24), 2);
        this.add(list, new ItemStack(Material.MYCEL, 20), 1);
        items.add(list);
        return items;
    }

    protected List<ItemStack> getCommonItems() {
        List<ItemStack> items = new ArrayList();
        this.add(items, new SimpleItemStack(Material.IRON_AXE, "&fЖелезный топор"), 12);
        this.add(items, new SimpleItemStack(Material.IRON_PICKAXE, "&fЖелезная кирка"), 12);
        this.add(items, new SimpleItemStack(Material.IRON_SWORD, "&fЖелезный меч"), 15);
        this.add(items, new SimpleItemStack(Material.IRON_SWORD, "&fЖелезный меч"), 10);
        this.add(items, new SimpleItemStack(Material.IRON_SWORD, "&fЖелезный меч"), 10);
        this.add(items, new SimpleItemStack(Material.IRON_SWORD, "&fЖелезный меч"), 10);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 2);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_FIRE, 1}), 8);
        this.add(items, new ItemStack(Material.ARROW, 16), 15);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HOE, "&fАлмазная мотыга", new Object[]{Enchantment.KNOCKBACK, 2}), 2);
        this.add(items, new ItemStack(Material.SNOW_BALL, 10), 12);
        this.add(items, new ItemStack(Material.EGG, 10), 10);
        this.add(items, new ItemStack(Material.FISHING_ROD, 1), 5);
        this.add(items, new ItemStack(Material.WOOD, 16), 14);
        this.add(items, new ItemStack(Material.WOOD, 32), 12);
        this.add(items, new ItemStack(Material.STONE, 24), 10);
        this.add(items, new ItemStack(Material.STONE, 48), 8);
        this.add(items, new ItemStack(Material.DIRT, 18), 10);
        this.add(items, new ItemStack(Material.DIRT, 36), 8);
        this.add(items, new ItemStack(Material.TNT, 4), 4);
        this.add(items, new ItemStack(Material.EXP_BOTTLE, 16), 8);
        this.add(items, new ItemStack(Material.EXP_BOTTLE, 32), 6);
        this.add(items, new ItemStack(Material.ENCHANTMENT_TABLE, 1), 4);
        this.add(items, new ItemStack(Material.STONE_PLATE, 1), 6);
        this.add(items, new ItemStack(Material.WATER_BUCKET, 1), 6);
        this.add(items, new ItemStack(Material.LAVA_BUCKET, 1), 4);
        this.add(items, new SimpleItemStack(Material.IRON_HELMET, "&fЖелезный шлем"), 12);
        this.add(items, new SimpleItemStack(Material.IRON_CHESTPLATE, "&fЖелезный нагрудник"), 12);
        this.add(items, new SimpleItemStack(Material.IRON_LEGGINGS, "&fЖелезные штаны"), 12);
        this.add(items, new SimpleItemStack(Material.IRON_BOOTS, "&fЖелезные ботинки"), 12);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем"), 3);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник"), 5);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны"), 5);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки"), 5);
        this.add(items, new ItemStack(Material.COOKED_BEEF, 16), 10);
        this.add(items, new ItemStack(Material.COOKED_BEEF, 32), 8);
        this.add(items, new ItemStack(Material.BAKED_POTATO, 16), 10);
        this.add(items, new ItemStack(Material.BAKED_POTATO, 32), 8);
        this.add(items, new ItemStack(Material.GOLDEN_APPLE, 2), 2);
        this.add(items, new ItemStack(Material.GOLDEN_APPLE, 3), 1);
        this.add(items, new ItemStack(Material.ENDER_PEARL, 2), 4);
        this.add(items, new SimpleItemStack(Material.SLIME_BALL, "&aСгусток слизи", new Object[]{Enchantment.KNOCKBACK, 10}), 1);
        return items;
    }

    protected List<ItemStack> getCenterItems() {
        List<ItemStack> items = new ArrayList();
        this.add(items, new SimpleItemStack(Material.IRON_PICKAXE, "&fЖелезная кирка", new Object[]{Enchantment.DIG_SPEED, 3}), 5);
        this.add(items, new SimpleItemStack(Material.DIAMOND_PICKAXE, "&fАлмазная кирка", new Object[]{Enchantment.DIG_SPEED, 3}), 3);
        this.add(items, new SimpleItemStack(Material.IRON_SWORD, "&fЖелезный меч", new Object[]{Enchantment.DAMAGE_ALL, 2}), 5);
        this.add(items, new SimpleItemStack(Material.IRON_SWORD, "&fЖелезный меч", new Object[]{Enchantment.DAMAGE_ALL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_SWORD, "&fЖелезный меч", new Object[]{Enchantment.DAMAGE_ALL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_SWORD, "&fЖелезный меч", new Object[]{Enchantment.DAMAGE_ALL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.FIRE_ASPECT, 2}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 1}), 3);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&bАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&bАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&bАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_FIRE, 1, Enchantment.ARROW_DAMAGE, 3}), 7);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_DAMAGE, 1}), 6);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.KNOCKBACK, 2}), 3);
        this.add(items, new ItemStack(Material.ARROW, 16), 7);
        this.add(items, new ItemStack(Material.ARROW, 24), 6);
        this.add(items, new ItemStack(Material.SNOW_BALL, 16), 3);
        this.add(items, new ItemStack(Material.SNOW_BALL, 40), 2);
        this.add(items, new ItemStack(Material.EGG, 16), 3);
        this.add(items, new ItemStack(Material.EGG, 40), 2);
        this.add(items, new ItemStack(Material.FISHING_ROD, 1), 5);
        this.add(items, new SimpleItemStack(Material.FISHING_ROD, "&fУдочка", new Object[]{Enchantment.KNOCKBACK, 2}), 2);
        this.add(items, new SimpleItemStack(Material.SLIME_BALL, "&aСгусток слизи", new Object[]{Enchantment.KNOCKBACK, 10}), 1);
        this.add(items, new ItemStack(Material.WOOD, 16), 4);
        this.add(items, new ItemStack(Material.WOOD, 32), 3);
        this.add(items, new ItemStack(Material.STONE, 24), 5);
        this.add(items, new ItemStack(Material.STONE, 48), 4);
        this.add(items, new ItemStack(Material.DIRT, 18), 5);
        this.add(items, new ItemStack(Material.DIRT, 36), 5);
        this.add(items, new SimpleItemStack(Material.IRON_HELMET, "&fЖелезный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 1, Enchantment.DURABILITY, 2}), 2);
        this.add(items, new SimpleItemStack(Material.IRON_CHESTPLATE, "&fЖелезный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 1, Enchantment.DURABILITY, 2}), 2);
        this.add(items, new SimpleItemStack(Material.IRON_LEGGINGS, "&fЖелезные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 1, Enchantment.DURABILITY, 2}), 2);
        this.add(items, new SimpleItemStack(Material.IRON_BOOTS, "&fЖелезные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 1, Enchantment.DURABILITY, 2}), 2);
        this.add(items, new SimpleItemStack(Material.IRON_HELMET, "&fЖелезный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.DURABILITY, 2}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_CHESTPLATE, "&fЖелезный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.DURABILITY, 2}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_LEGGINGS, "&fЖелезные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.DURABILITY, 2}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_BOOTS, "&fЖелезные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.DURABILITY, 2}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_HELMET, "&fЖелезный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3, Enchantment.DURABILITY, 2}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_CHESTPLATE, "&fЖелезный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3, Enchantment.DURABILITY, 2}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_LEGGINGS, "&fЖелезные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3, Enchantment.DURABILITY, 2}), 1);
        this.add(items, new SimpleItemStack(Material.IRON_BOOTS, "&fЖелезные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3, Enchantment.DURABILITY, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем"), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник"), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны"), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки"), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем", new Object[]{Enchantment.PROTECTION_PROJECTILE, 4}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_PROJECTILE, 4}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны", new Object[]{Enchantment.PROTECTION_PROJECTILE, 4}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки", new Object[]{Enchantment.PROTECTION_PROJECTILE, 4}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.PROTECTION_FIRE, 2}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.PROTECTION_FIRE, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.PROTECTION_FIRE, 2}), 3);
        this.add(items, new ItemStack(Material.ENDER_PEARL, 2), 2);
        this.add(items, new ItemStack(Material.ENDER_PEARL, 5), 2);
        return items;
    }
}