package net.villenium.skywars.game.generators;

import net.villenium.skywars.utils.simple.SimpleItemStack;
import org.bukkit.Material;
import org.bukkit.enchantments.Enchantment;
import org.bukkit.inventory.ItemStack;

import java.util.ArrayList;
import java.util.List;

public class InsaneGenerator extends ChestGenerator {
    public InsaneGenerator() {
        super(5, 10);
    }

    protected List<List<ItemStack>> getDefaultItems() {
        List<List<ItemStack>> items = new ArrayList();
        List<ItemStack> list = new ArrayList();
        this.add(list, new ItemStack(Material.IRON_SWORD, 1), 1);
        this.add(list, new ItemStack(Material.DIAMOND_SWORD, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.IRON_HELMET, 1), 2);
        this.add(list, new ItemStack(Material.DIAMOND_HELMET, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.IRON_CHESTPLATE, 1), 2);
        this.add(list, new ItemStack(Material.DIAMOND_CHESTPLATE, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.IRON_LEGGINGS, 1), 2);
        this.add(list, new ItemStack(Material.DIAMOND_LEGGINGS, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.IRON_BOOTS, 1), 2);
        this.add(list, new ItemStack(Material.DIAMOND_BOOTS, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.EGG, 16), 2);
        this.add(list, new ItemStack(Material.SNOW_BALL, 16), 2);
        this.add(list, new ItemStack(Material.FISHING_ROD, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.COOKED_BEEF, 32), 1);
        this.add(list, new ItemStack(Material.COOKED_CHICKEN, 48), 1);
        this.add(list, new ItemStack(Material.COOKED_FISH, 32), 1);
        this.add(list, new ItemStack(Material.APPLE, 64), 2);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.WATER_BUCKET, 1), 4);
        this.add(list, new ItemStack(Material.LAVA_BUCKET, 1), 2);
        this.add(list, new ItemStack(Material.ENCHANTMENT_TABLE, 1), 2);
        this.add(list, new ItemStack(Material.SANDSTONE, 64), 2);
        this.add(list, new ItemStack(Material.SAND, 64), 1);
        this.add(list, new ItemStack(Material.IRON_PICKAXE, 1), 2);
        this.add(list, new ItemStack(Material.IRON_AXE, 1), 1);
        items.add(list);
        list = new ArrayList();
        this.add(list, new ItemStack(Material.WOOD, 64), 4);
        this.add(list, new ItemStack(Material.STONE, 64), 2);
        this.add(list, new ItemStack(Material.MYCEL, 64), 1);
        items.add(list);
        return items;
    }

    protected List<ItemStack> getCommonItems() {
        List<ItemStack> items = new ArrayList();
        this.add(items, new SimpleItemStack(Material.DIAMOND_AXE, "&fАлмазный топор"), 12);
        this.add(items, new SimpleItemStack(Material.DIAMOND_PICKAXE, "&fАлмазная кирка"), 12);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 15);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч"), 3);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 1}), 15);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 2}), 7);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_FIRE, 1}), 12);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_FIRE, 1, Enchantment.ARROW_DAMAGE, 1}), 8);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_DAMAGE, 2}), 6);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_FIRE, 1, Enchantment.ARROW_DAMAGE, 2}), 4);
        this.add(items, new ItemStack(Material.ARROW, 48), 15);
        this.add(items, new ItemStack(Material.ARROW, 32), 7);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HOE, "&fАлмазная мотыга", new Object[]{Enchantment.KNOCKBACK, 2}), 4);
        this.add(items, new ItemStack(Material.SNOW_BALL, 16), 12);
        this.add(items, new ItemStack(Material.EGG, 16), 10);
        this.add(items, new ItemStack(Material.FISHING_ROD, 1), 5);
        this.add(items, new ItemStack(Material.WOOD, 32), 14);
        this.add(items, new ItemStack(Material.WOOD, 48), 12);
        this.add(items, new ItemStack(Material.STONE, 48), 10);
        this.add(items, new ItemStack(Material.STONE, 64), 8);
        this.add(items, new ItemStack(Material.DIRT, 32), 10);
        this.add(items, new ItemStack(Material.DIRT, 64), 8);
        this.add(items, new ItemStack(Material.TNT, 8), 4);
        this.add(items, new ItemStack(Material.EXP_BOTTLE, 32), 8);
        this.add(items, new ItemStack(Material.EXP_BOTTLE, 64), 6);
        this.add(items, new ItemStack(Material.ENCHANTMENT_TABLE, 1), 4);
        this.add(items, new ItemStack(Material.STONE_PLATE, 1), 6);
        this.add(items, new ItemStack(Material.WATER_BUCKET, 1), 6);
        this.add(items, new ItemStack(Material.LAVA_BUCKET, 1), 4);
        this.add(items, new SimpleItemStack(Material.IRON_HELMET, "&fЖелезный шлем"), 12);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем"), 6);
        this.add(items, new SimpleItemStack(Material.IRON_CHESTPLATE, "&fЖелезный нагрудник"), 12);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник"), 6);
        this.add(items, new SimpleItemStack(Material.IRON_LEGGINGS, "&fЖелезные штаны"), 12);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны"), 6);
        this.add(items, new SimpleItemStack(Material.IRON_BOOTS, "&fЖелезные ботинки"), 12);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки"), 6);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 1}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 1}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 1}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 1}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2}), 2);
        this.add(items, new ItemStack(Material.COOKED_BEEF, 32), 10);
        this.add(items, new ItemStack(Material.COOKED_BEEF, 48), 8);
        this.add(items, new ItemStack(Material.BAKED_POTATO, 32), 10);
        this.add(items, new ItemStack(Material.BAKED_POTATO, 64), 8);
        this.add(items, new ItemStack(Material.GOLDEN_APPLE, 4), 2);
        this.add(items, new ItemStack(Material.GOLDEN_APPLE, 6), 1);
        this.add(items, new ItemStack(Material.ENDER_PEARL, 2), 4);
        this.add(items, new SimpleItemStack(Material.SLIME_BALL, "&a&lСгусток слизи", new Object[]{Enchantment.KNOCKBACK, 10}), 1);
        return items;
    }

    protected List<ItemStack> getCenterItems() {
        List<ItemStack> items = new ArrayList();
        this.add(items, new SimpleItemStack(Material.DIAMOND_PICKAXE, "&fАлмазная кирка", new Object[]{Enchantment.DIG_SPEED, 2}), 5);
        this.add(items, new SimpleItemStack(Material.DIAMOND_PICKAXE, "&fАлмазная кирка", new Object[]{Enchantment.DIG_SPEED, 4}), 3);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 1}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 1}), 3);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 2}), 3);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.FIRE_ASPECT, 2}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.FIRE_ASPECT, 2}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.FIRE_ASPECT, 1, Enchantment.DAMAGE_ALL, 2}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 3}), 3);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&fАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 4}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_SWORD, "&bАлмазный меч", new Object[]{Enchantment.DAMAGE_ALL, 5}), 1);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_FIRE, 1, Enchantment.ARROW_DAMAGE, 3}), 7);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_DAMAGE, 3}), 2);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.ARROW_DAMAGE, 4}), 2);
        this.add(items, new SimpleItemStack(Material.BOW, "&4&lЛук", new Object[]{Enchantment.ARROW_DAMAGE, 5}), 1);
        this.add(items, new SimpleItemStack(Material.BOW, "&fЛук", new Object[]{Enchantment.KNOCKBACK, 2, Enchantment.ARROW_DAMAGE, 2}), 3);
        this.add(items, new SimpleItemStack(Material.BOW, "&4&lЛук", new Object[]{Enchantment.KNOCKBACK, 2, Enchantment.ARROW_DAMAGE, 2, Enchantment.ARROW_FIRE, 1}), 1);
        this.add(items, new ItemStack(Material.ARROW, 32), 7);
        this.add(items, new ItemStack(Material.ARROW, 48), 6);
        this.add(items, new ItemStack(Material.SNOW_BALL, 32), 3);
        this.add(items, new ItemStack(Material.SNOW_BALL, 64), 2);
        this.add(items, new ItemStack(Material.EGG, 32), 3);
        this.add(items, new ItemStack(Material.EGG, 64), 2);
        this.add(items, new ItemStack(Material.FISHING_ROD, 1), 5);
        this.add(items, new SimpleItemStack(Material.FISHING_ROD, "&fУдочка", new Object[]{Enchantment.KNOCKBACK, 2}), 4);
        this.add(items, new SimpleItemStack(Material.SLIME_BALL, "&a&lСгусток слизи", new Object[]{Enchantment.KNOCKBACK, 10}), 2);
        this.add(items, new ItemStack(Material.WOOD, 32), 4);
        this.add(items, new ItemStack(Material.WOOD, 64), 3);
        this.add(items, new ItemStack(Material.STONE, 48), 5);
        this.add(items, new ItemStack(Material.STONE, 64), 4);
        this.add(items, new ItemStack(Material.DIRT, 32), 5);
        this.add(items, new ItemStack(Material.DIRT, 64), 5);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки"), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.PROTECTION_PROJECTILE, 4}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.PROTECTION_PROJECTILE, 4}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.PROTECTION_PROJECTILE, 4}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&fАлмазные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 2, Enchantment.PROTECTION_PROJECTILE, 4}), 4);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&fАлмазный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3, Enchantment.PROTECTION_FIRE, 3}), 2);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&fАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3, Enchantment.PROTECTION_FIRE, 3}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&fАлмазные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 3, Enchantment.PROTECTION_FIRE, 3}), 3);
        this.add(items, new SimpleItemStack(Material.DIAMOND_HELMET, "&4&lАлмазный шлем", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 4, Enchantment.PROTECTION_PROJECTILE, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_CHESTPLATE, "&4&lАлмазный нагрудник", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 4, Enchantment.PROTECTION_PROJECTILE, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_LEGGINGS, "&4&lАлмазные штаны", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 4, Enchantment.PROTECTION_PROJECTILE, 2}), 1);
        this.add(items, new SimpleItemStack(Material.DIAMOND_BOOTS, "&4&lАлмазные ботинки", new Object[]{Enchantment.PROTECTION_ENVIRONMENTAL, 4, Enchantment.PROTECTION_PROJECTILE, 2}), 1);
        this.add(items, new ItemStack(Material.ENDER_PEARL, 2), 2);
        this.add(items, new ItemStack(Material.ENDER_PEARL, 5), 2);
        return items;
    }
}