package net.villenium.skywars.game;

import net.villenium.skywars.enums.Rarity;
import org.bukkit.Material;
import org.bukkit.material.MaterialData;

import java.util.HashMap;
import java.util.Map;

public class CageManager {
    private static final Map<String, Cage> cages;
    private static final Cage defaultCage;

    static {
        cages = new HashMap<String, Cage>();
        defaultCage = new Cage("Default", "Default", null, new MaterialData(Material.GLASS));
    }

    public static void init() {
        add(new Cage("Banana", "Банана клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 4)));
        add(new Cage("Bubblegum", "БаблГам клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 6)));
        add(new Cage("Cloud", "Облачная клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 7)));
        add(new Cage("Green", "Зеленая клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 13)));
        add(new Cage("Lime", "Лаймовая клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 5)));
        add(new Cage("Mist", "Туманная клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 8)));
        add(new Cage("Red", "Красная клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 14)));
        add(new Cage("Orange", "Оранжевая клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 1)));
        add(new Cage("LightBlue", "Голубая клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 3)));
        add(new Cage("Blue", "Синяя клетка", Rarity.COMMON, new MaterialData(Material.STAINED_GLASS, (byte) 11)));
        add(new Cage("Royal", "Королевская клетка", Rarity.RARE, new MaterialData(Material.GOLD_BLOCK), new MaterialData[]{new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GLASS), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GLASS), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK), new MaterialData(Material.GOLD_BLOCK)}));
        add(new Cage("Demonic", "Демоническая клетка", Rarity.RARE, new MaterialData(Material.NETHERRACK), new MaterialData[]{new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.GLASS), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.GLASS), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK), new MaterialData(Material.NETHERRACK)}));
        add(new Cage("Angel", "Ангельская клетка", Rarity.RARE, new MaterialData(Material.QUARTZ_BLOCK), new MaterialData[]{new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.GLASS), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.GLASS), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.GLASS), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK), new MaterialData(Material.QUARTZ_BLOCK)}));
        add(new Cage("Rainbow", "Радужная клетка", Rarity.EPIC, new MaterialData(Material.BREWING_STAND_ITEM), new MaterialData[]{new MaterialData(Material.STAINED_GLASS, (byte) 14), new MaterialData(Material.STAINED_GLASS, (byte) 1), new MaterialData(Material.STAINED_GLASS, (byte) 4), new MaterialData(Material.STAINED_GLASS, (byte) 5), new MaterialData(Material.STAINED_GLASS, (byte) 13), new MaterialData(Material.STAINED_GLASS, (byte) 3), new MaterialData(Material.STAINED_GLASS, (byte) 11), new MaterialData(Material.STAINED_GLASS, (byte) 2), new MaterialData(Material.STAINED_GLASS, (byte) 10), new MaterialData(Material.STAINED_GLASS, (byte) 13), new MaterialData(Material.STAINED_GLASS, (byte) 5), new MaterialData(Material.STAINED_GLASS, (byte) 4), new MaterialData(Material.STAINED_GLASS, (byte) 1), new MaterialData(Material.STAINED_GLASS, (byte) 14), new MaterialData(Material.STAINED_GLASS, (byte) 10), new MaterialData(Material.STAINED_GLASS, (byte) 2), new MaterialData(Material.STAINED_GLASS, (byte) 11), new MaterialData(Material.STAINED_GLASS, (byte) 3), new MaterialData(Material.STAINED_GLASS, (byte) 3), new MaterialData(Material.STAINED_GLASS, (byte) 11), new MaterialData(Material.STAINED_GLASS, (byte) 2), new MaterialData(Material.STAINED_GLASS, (byte) 10), new MaterialData(Material.STAINED_GLASS, (byte) 14), new MaterialData(Material.STAINED_GLASS, (byte) 1), new MaterialData(Material.STAINED_GLASS, (byte) 4), new MaterialData(Material.STAINED_GLASS, (byte) 5), new MaterialData(Material.STAINED_GLASS, (byte) 13), new MaterialData(Material.STAINED_GLASS, (byte) 10), new MaterialData(Material.STAINED_GLASS, (byte) 2), new MaterialData(Material.STAINED_GLASS, (byte) 1), new MaterialData(Material.STAINED_GLASS, (byte) 3), new MaterialData(Material.STAINED_GLASS, (byte) 13), new MaterialData(Material.STAINED_GLASS, (byte) 5), new MaterialData(Material.STAINED_GLASS, (byte) 4), new MaterialData(Material.STAINED_GLASS, (byte) 1), new MaterialData(Material.STAINED_GLASS, (byte) 14)}));
        add(new Cage("Ice", "Ледяная клетка", Rarity.RARE, new MaterialData(Material.ICE)));
        add(new Cage("Slime", "Клетка из слизи", Rarity.EPIC, new MaterialData(Material.SLIME_BLOCK)));
        add(new Cage("Invisible", "Невидимая клетка", Rarity.LEGENDARY, new MaterialData(Material.BARRIER)));
        add(new Cage("Striped", "Зебра-клетка", Rarity.RARE, new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData[]{new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 0), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15), new MaterialData(Material.STAINED_GLASS, (byte) 15)}));
        add(new Cage("Wooden", "Деревянная клетка", Rarity.EPIC, new MaterialData(Material.FENCE), new MaterialData[]{new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.WOOD), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.WOOD), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE), new MaterialData(Material.FENCE)}));
        add(new Cage("Iron", "Железная клетка", Rarity.EPIC, new MaterialData(Material.IRON_FENCE), new MaterialData[]{new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_BLOCK), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_BLOCK), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE), new MaterialData(Material.IRON_FENCE)}));
    }

    private static void add(final Cage cage) {
        CageManager.cages.put(cage.getName(), cage);
    }

    public static Map<String, Cage> getCages() {
        return CageManager.cages;
    }

    public static Cage getDefaultCage() {
        return CageManager.defaultCage;
    }
}
